//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELogistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freight
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Lenght { get; set; }
        public Nullable<int> DestinationAddressId { get; set; }
        public Nullable<int> OriginAddressId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
