//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELogistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int Id { get; set; }
        public string Status1 { get; set; }
        public Nullable<System.DateTime> DatePickedUp { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public Nullable<int> DriverId { get; set; }
    }
}
